apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener Calico Network Extension
name: gardener-extension-networking-calico
version: 0.1.0
sources:
- https://github.com/gardener/gardener-extension-networking-calico
