{{- if and .Values.config.monitoring.enabled .Values.config.birdExporter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: calico-bird-monitoring
  namespace: kube-system
spec:
  ports:
    - port: {{ .Values.config.monitoring.birdMetricsPort }}
      targetPort: {{ .Values.config.monitoring.birdMetricsPort }}
  selector:
    k8s-app: calico-node
{{- end }}
