//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-networking-calico/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	configv1alpha1 "k8s.io/component-base/config/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubeAPIServerGlobalNetworkSetConfiguration)(nil), (*config.KubeAPIServerGlobalNetworkSetConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration_To_config_KubeAPIServerGlobalNetworkSetConfiguration(a.(*KubeAPIServerGlobalNetworkSetConfiguration), b.(*config.KubeAPIServerGlobalNetworkSetConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.KubeAPIServerGlobalNetworkSetConfiguration)(nil), (*KubeAPIServerGlobalNetworkSetConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_KubeAPIServerGlobalNetworkSetConfiguration_To_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration(a.(*config.KubeAPIServerGlobalNetworkSetConfiguration), b.(*KubeAPIServerGlobalNetworkSetConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*configv1alpha1.ClientConnectionConfiguration)(unsafe.Pointer(in.ClientConnection))
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.KubeAPIServerGlobalNetworkSet = (*config.KubeAPIServerGlobalNetworkSetConfiguration)(unsafe.Pointer(in.KubeAPIServerGlobalNetworkSet))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*configv1alpha1.ClientConnectionConfiguration)(unsafe.Pointer(in.ClientConnection))
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.KubeAPIServerGlobalNetworkSet = (*KubeAPIServerGlobalNetworkSetConfiguration)(unsafe.Pointer(in.KubeAPIServerGlobalNetworkSet))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration_To_config_KubeAPIServerGlobalNetworkSetConfiguration(in *KubeAPIServerGlobalNetworkSetConfiguration, out *config.KubeAPIServerGlobalNetworkSetConfiguration, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration_To_config_KubeAPIServerGlobalNetworkSetConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration_To_config_KubeAPIServerGlobalNetworkSetConfiguration(in *KubeAPIServerGlobalNetworkSetConfiguration, out *config.KubeAPIServerGlobalNetworkSetConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration_To_config_KubeAPIServerGlobalNetworkSetConfiguration(in, out, s)
}

func autoConvert_config_KubeAPIServerGlobalNetworkSetConfiguration_To_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration(in *config.KubeAPIServerGlobalNetworkSetConfiguration, out *KubeAPIServerGlobalNetworkSetConfiguration, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_config_KubeAPIServerGlobalNetworkSetConfiguration_To_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration is an autogenerated conversion function.
func Convert_config_KubeAPIServerGlobalNetworkSetConfiguration_To_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration(in *config.KubeAPIServerGlobalNetworkSetConfiguration, out *KubeAPIServerGlobalNetworkSetConfiguration, s conversion.Scope) error {
	return autoConvert_config_KubeAPIServerGlobalNetworkSetConfiguration_To_v1alpha1_KubeAPIServerGlobalNetworkSetConfiguration(in, out, s)
}
