//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-networking-calico/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	configv1alpha1 "k8s.io/component-base/config/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubeAPIServerEndpointsConfiguration)(nil), (*config.KubeAPIServerEndpointsConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubeAPIServerEndpointsConfiguration_To_config_KubeAPIServerEndpointsConfiguration(a.(*KubeAPIServerEndpointsConfiguration), b.(*config.KubeAPIServerEndpointsConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.KubeAPIServerEndpointsConfiguration)(nil), (*KubeAPIServerEndpointsConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_KubeAPIServerEndpointsConfiguration_To_v1alpha1_KubeAPIServerEndpointsConfiguration(a.(*config.KubeAPIServerEndpointsConfiguration), b.(*KubeAPIServerEndpointsConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*configv1alpha1.ClientConnectionConfiguration)(unsafe.Pointer(in.ClientConnection))
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.KubeAPIServerEndpoints = (*config.KubeAPIServerEndpointsConfiguration)(unsafe.Pointer(in.KubeAPIServerEndpoints))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*configv1alpha1.ClientConnectionConfiguration)(unsafe.Pointer(in.ClientConnection))
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.KubeAPIServerEndpoints = (*KubeAPIServerEndpointsConfiguration)(unsafe.Pointer(in.KubeAPIServerEndpoints))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KubeAPIServerEndpointsConfiguration_To_config_KubeAPIServerEndpointsConfiguration(in *KubeAPIServerEndpointsConfiguration, out *config.KubeAPIServerEndpointsConfiguration, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_KubeAPIServerEndpointsConfiguration_To_config_KubeAPIServerEndpointsConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_KubeAPIServerEndpointsConfiguration_To_config_KubeAPIServerEndpointsConfiguration(in *KubeAPIServerEndpointsConfiguration, out *config.KubeAPIServerEndpointsConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeAPIServerEndpointsConfiguration_To_config_KubeAPIServerEndpointsConfiguration(in, out, s)
}

func autoConvert_config_KubeAPIServerEndpointsConfiguration_To_v1alpha1_KubeAPIServerEndpointsConfiguration(in *config.KubeAPIServerEndpointsConfiguration, out *KubeAPIServerEndpointsConfiguration, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_config_KubeAPIServerEndpointsConfiguration_To_v1alpha1_KubeAPIServerEndpointsConfiguration is an autogenerated conversion function.
func Convert_config_KubeAPIServerEndpointsConfiguration_To_v1alpha1_KubeAPIServerEndpointsConfiguration(in *config.KubeAPIServerEndpointsConfiguration, out *KubeAPIServerEndpointsConfiguration, s conversion.Scope) error {
	return autoConvert_config_KubeAPIServerEndpointsConfiguration_To_v1alpha1_KubeAPIServerEndpointsConfiguration(in, out, s)
}
