{{- if .Values.config.multus.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni-config
  namespace: kube-system
data:
  cni-conf.json: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-cni-network",
      "binDir": "/opt/cni/bin",
      "cniDir": "/var/lib/cni/multus",
      "logFile": "/var/log/multus.log",
      "logLevel": "verbose",
      "logToStderr": true,
      "capabilities": {
        "portMappings": true
      },
      "namespaceIsolation": false,
      "clusterNetwork": "/etc/cni/net.d/10-calico.conflist",
      "type": "multus",
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "allowTryDeleteOnErr": true
    }
    {{- end }}
