image:
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/admission-calico
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}
metricsPort: 8080
healthPort: 8081
vpa:
  enabled: true
  resourcePolicy:
#     minAllowed:
#       memory: 64Mi
    controlledValues: RequestsOnly
  updatePolicy:
    updateMode: "Recreate"
webhookConfig:
  serverPort: 10250
# Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
kubeconfig:

#projectedKubeconfig:
#  baseMountPath: /var/run/secrets/gardener.cloud
#  genericKubeconfigSecretName: generic-token-kubeconfig
#  tokenSecretName: access-calico-admission

service:
  topologyAwareRouting:
    enabled: false

gardener:
  virtualCluster:
    enabled: true
    serviceAccount: {}
#     name: gardener-extension-admission-calico
#     namespace: kube-system
  runtimeCluster: {}
#   priorityClassName: gardener-garden-system-400