apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster

# data from landscape-*-setup/landscape.yaml section gardener-extension-networking-calico
- name: controllerRegistration
  schema:
    type: object
    properties:
      concurrentSyncs:
        type: integer
      resources:
        type: object
        properties:
          requests:
            type: object
            properties:
              cpu:
                type: string
              memory:
                type: string
          limits:
            type: object
            properties:
              cpu:
                type: string
              memory:
                type: string
      vpa:
        scheme:
          type: object

- name: imageVectorOverwrite
  schema:
    type: object
    properties:
      images:
        type: array
        items:
          type: object

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /deploy-executions.yaml
  name: manifests
  type: GoTemplate
