{{- if .Values.config.typha.enabled }}
{{- if not .Values.vpa.typha }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: typha-cpva
  namespace: kube-system
automountServiceAccountToken: false
{{- end }}
{{- end }}
