{{- if not .Values.gep19Monitoring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-monitoring-config
  namespace: {{ .Release.Namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  scrape_config: |
    - job_name: 'felix-metrics'
      scheme: https
      tls_config:
        # This is needed because the kubelets' certificates are not are generated
        # for a specific pod IP
        insecure_skip_verify: true
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      kubernetes_sd_configs:
      - role: endpoints
        api_server: https://kube-apiserver:443
        namespaces:
          names: [kube-system]
        tls_config:
          ca_file: /etc/prometheus/seed/ca.crt
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_pod_container_port_name]
        regex: calico-felix-monitoring;metrics
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - target_label: __address__
        replacement: kube-apiserver:443
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
        regex: (.+);(.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/pods/${1}:${2}/proxy/metrics
      metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: felix_.+
        action: keep

    - job_name: 'typha-metrics'
      scheme: https
      tls_config:
        # This is needed because the kubelets' certificates are not are generated
        # for a specific pod IP
        insecure_skip_verify: true
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      kubernetes_sd_configs:
      - role: endpoints
        api_server: https://kube-apiserver:443
        namespaces:
          names: [kube-system]
        tls_config:
         ca_file: /etc/prometheus/seed/ca.crt
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_pod_container_port_name]
        regex: calico-typha-monitoring;metrics
        action: keep
      - target_label: __address__
        replacement: kube-apiserver:443
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
        regex: (.+);(.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/pods/${1}:${2}/proxy/metrics
      metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: typha_.+
        action: keep

  dashboard_operators: |
    calico-felix-dashboard.json: |-
    {{- .Files.Get "calico-felix-dashboard.json" | nindent 6 }}

    calico-typha-dashboard.json: |-
    {{- .Files.Get "calico-typha-dashboard.json" | nindent 6 }}
{{- end }}
