{
 "title": "Felix Dashboard (Calico)",
 "description": "Felix dashboard is part of calico documentation website, you will have great insight about you Calico instance by using this dashboard.",
 "tags": [
  "calico",
  "felix",
  "kubernetes",
  "k8s",
  "calico-node",
  "cloud",
  "cluster monitoring",
  "policy monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Alerts and general info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active hosts on each node",
   "type": "gauge",
   "description": "These metrics are part of general information related to Calico implementation.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "felix_active_local_endpoints", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "iptables save errors",
   "type": "singlestat",
   "description": "Errors resulting from executing iptables-save, this can indicate an underlying problem in iptables.",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ipset errors",
   "type": "singlestat",
   "description": "Indicates a problem during creation of iptable address set blocks.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(felix_ipset_errors[5m]))"
    }
   ]
  },
  {
   "title": "Active calico nodes",
   "type": "singlestat",
   "description": "Active nodes should match the number of Kubernetes nodes. ",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(felix_cluster_num_hosts)", "legendFormat": "Calico node" }
   ]
  },
  {
   "title": "Errors plot",
   "type": "graph",
   "description": "This graph shows you all the errors that Calico encounters, it is important to note occasional errors are acceptable. However, rise in the number of error or constant error counters means Calico is not working properly.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(felix_ipset_errors[5m])", "legendFormat": "{{instance}} ipset errors" },
    {
     "expr": "rate(felix_iptables_restore_errors[5m])",
     "legendFormat": "{{instance}} iptables restore errors"
    },
    {
     "expr": "rate(felix_iptables_save_errors[5m])",
     "legendFormat": "{{instance}} iptables save errors"
    },
    { "expr": "rate(felix_log_errors[5m])", "legendFormat": "{{instance}} log errors" }
   ]
  },
  {
   "title": "Felix cluster policies",
   "type": "gauge",
   "description": "More policies on Felix means more effort required by Calico to manage packets. ",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "felix_cluster_num_policies", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "iptables restore errors",
   "type": "singlestat",
   "description": "Indicates a problem trying to restore Calico iptables/",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_restore_errors[5m]))"
    }
   ]
  },
  {
   "title": "Felix log errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(felix_log_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix resync started",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(felix_resyncs_started[5m])) "
    }
   ]
  },
  {
   "title": "Felix dropped logs",
   "type": "graph",
   "description": "This graph shows you all the felix dropped  errors that Calico encounters, it is important to note occasional errors are acceptable. However, rise in the number of error or constant error counters means Calico is not working properly.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_logs_dropped", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dataplane apply time quantile 0.5",
   "type": "graph",
   "description": "Dataplane apply time can indicate how busy your Kubernetes instance is. This can slow down Calico performance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane apply time quantile 0.9",
   "type": "graph",
   "description": "Dataplane apply time can indicate how busy your Kubernetes instance is. This can slow down Calico performance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane apply time quantile 0.99",
   "type": "graph",
   "description": "Dataplane apply time can indicate how busy your Kubernetes instance is. This can slow down Calico performance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Route table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Felix route table list seconds quantile 0.5",
   "type": "graph",
   "description": "50% percentile for the time taken to list all the interfaces during a resync.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_route_table_list_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix route table list seconds quantile 0.9",
   "type": "graph",
   "description": "90% percentile for the time taken to list all the interfaces during a resync.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_route_table_list_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix route table list seconds quantile 0.99",
   "type": "graph",
   "description": "99% percentile for the time taken to list all the interfaces during a resync.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_route_table_list_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}